### ISSUE TITLE
Coin selection algorithm

### ISSUE THREAD

**Issue by gege251** [mlabs-haskell/bot-plutus-interface#32]
We don't have any sophisticated coin selection working at the moment, the order in which pre balance pick utxos for the inputs is based on the order they appear on the cli. This could cause problems, when there are a lot of dust utxos, or the token we are looking for is too much down the list. In worst cases, this could bloat the tx size, fees, or even fail submitting.

**Comment by gege251** [comment]
There's actually a [CIP](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0002) for coin selection algorithms, but now that I read it more carefully, I realised that they don't account for native tokens.
To be honest I don't know, if we need a sophisticated coin selection atm, maybe it's enough to just avoid worst case scenarios.
For example, when there's a lot of dust in the wallet, containing only ada, but the coin selection algo goes looking for some other token and picks all these dust utxos into the input set.

**Comment by IAmPara0x** [comment]
Current Problems:

1. The current implemented algorithm is not-greedy, it doesn't organize the utxos in any kind of order.
   Hence, if we have native tokens at the bottom of utxos list we end up consuming all the utxos.

2. The problem with greedy algorithm is that it creates a lot of "dust" utxos, so it will lead to
   same problem as stated in point 1, i.e. after user has performed lots of transactions, there will lot
   of utxos with smaller values. So we will end up consuming lot of smaller utxos as input to "fill" one
   bigger utxo at Tx output.

3. Not clear a way on how to handle native tokens in greedy algorithm.


Proposed Algorithm for coin selection problem.

To take account for native tokens, we can reformulate the problem in the following way:

  we can think of a value with different native tokens as vectors of n-dimension.

  Eg:

   Values:

      value1: [("ScriptHash1", "TokenName1", 1), ("", "", 1)]
      value2: [("ScriptHash1", "TokenName1", 2), ("ScriptHash2", "TokenName2", 2), ("", "", 2)]

   Converting Values to vectors:

      value1vector: [1, 0, 1]
      value2vector: [2, 2, 2]

  Each element of the vector represents corresponding native tokens and ada, if a native token
  is not present in a value then we fill it with zero.


If we think of all the values as vector, then we can think of coin selection and balancing problem in the following way:

  we have an output vector and many input vectors, and the goal is to get as close to the output vector
  as possible using all the input vectors. Now, since we think of value as vectors we can define
  what "close" will be, which is just the euclidean distance.

  Eg: consider a Tx with two outputs and three utxos at user's wallet.

    output1 : [("scriptHash1", "TokenName1", 1), ("", "", 1)]
    output2 : [("", "", 2)]
    Fee     : [("", "", 3)]


    output-vector: [1, 6] -- Just Adding output1 + output2 + Fee


    utxo1 : [("scriptHash1", "TokenName1", 10), ("", "", 10)]
    utxo2 : [("", "", 5)]
    utxo3 : [("scriptHash1", "TokenName1", 3), ("", "", 6)]

    utxo1-vector: [10, 10]
    utxo2-vector: [0, 5]
    utxo3-vector: [3, 6]

    Now, as stated above our goal is to get as close to output-vector as possible by using different
    combinations of input vectors:

    distance(output-vector, utxo1-vector) = 9.848857801796104

    distance(output-vector, utxo2-vector + utxo3-vector) = 5.385164807134504

    As we can see, utxo1-vector and output-vector are very far apart, therefore we will not select that utxo.
    Whereas distance between output-vector and utxo2-vector + utxo3-vector is comparatively less, hence those
    utxos will be selected as Inputs.


This is the greedy version of the coin selection problem but the [random-improve](https://iohk.io/en/blog/posts/2018/07/03/self-organisation-in-coin-selection/) version of this can also
be formulated, in terms of vectors.

**Comment by mikekeke** [comment]
Done in #128
